site_name: KnowledgeCity Architecture
site_description: Documentation for the multi-regional cloud-native KnowledgeCity platform
site_author: Your Name
theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight
    - search.share

nav:
  - Home: index.md
  - Architecture:
      - Overview: architecture.md
      - Multi-Region Design: multi-region.md
      - Data Distribution: data-distribution.md
      - Scalability: scalability.md
      - Security: security.md
      - Compliance: compliance.md
  - Components:
      - Frontend: frontend.md
      - Monolith (PHP): monolith.md
      - Microservices: 
          - Analytics: analytics.md
          - Video Processing: video-processing.md
          - Media Handling: media.md
          - Video Delivery: video.md
  - DevOps & Tooling:
      - CI/CD: ci-cd.md
      - Observability: observability.md
      - Tooling & Stack: tooling.md
  - Planning:
      - Future Expansion: future-expansion.md
      - Future Considerations: future.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.tasklist

plugins:
  - search
