site_name: KnowledgeCity Platform Documentation
site_author: KnowledgeCity DevOps Team
site_description: Multi-regional, scalable, cloud-native documentation for a video learning platform.

theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.ico
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - navigation.footer

nav:
  - Home: index.md
  - Platform Overview:
      - Architecture: architecture.md
      - High-Level Diagram: high-level.png
      - Future Expansion: future-expansion.md
  - Infrastructure:
      - Scalability: scalability.md
      - Multi-Region: multi-region.md
      - Observability: observability.md
      - Compliance: compliance.md
  - Applications:
      - Frontend: frontend.md
      - Monolith: monolith.md
      - Analytics: analytics.md
      - Video Processing: video-processing.md
  - DevOps:
      - CI/CD: ci-cd.md
      - Data Distribution: data-distribution.md
      - Security: security.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
  - footnotes
  - tables
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.highlight
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - stylesheets/custom.css  # Optional

extra_javascript:
  - javascripts/custom.js   # Optional

repo_name: GitHub
edit_uri: blob/main/docs/

plugins:
  - search